# Generated by Django 3.0 on 2020-01-25 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='discussion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disc_date', models.DateTimeField(verbose_name='date published')),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Video.Membre')),
            ],
        ),
    ]
