# Generated by Django 3.0 on 2020-01-25 11:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='discussion_recv',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='discussion',
            name='discussion_send',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='disc_date',
            field=models.DateTimeField(verbose_name=django.utils.timezone.now),
        ),
    ]
